// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddClip(arg1:string,arg2:boolean):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DeleteAllClips():Promise<void>;

export function DeletePinnedClips():Promise<void>;

export function DeleteUnpinnedClips():Promise<void>;

export function GetClips():Promise<Array<main.Clip>>;

export function GetStorageLimit():Promise<number>;

export function GetVersion():Promise<string>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateStorageLimit(arg1:number):Promise<void>;
