// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AddClip(arg1:string,arg2:boolean):Promise<void>;

export function AddIgnoreEntry(arg1:string):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DeleteAllClips():Promise<void>;

export function DeletePinnedClips():Promise<void>;

export function DeleteUnpinnedClips():Promise<void>;

export function DisableStartup():Promise<void>;

export function EnableStartup():Promise<void>;

export function GetClips():Promise<Array<store.Clip>>;

export function GetGhostMode():Promise<boolean>;

export function GetIgnoreList():Promise<Array<string>>;

export function GetStorageLimit():Promise<number>;

export function GetVersion():Promise<string>;

export function IsMiniClip():Promise<boolean>;

export function IsPaused():Promise<boolean>;

export function IsStartupEnabled():Promise<boolean>;

export function MakeMiniClip(arg1:boolean):Promise<void>;

export function PasteToWindow(arg1:string):Promise<void>;

export function PauseCapture():Promise<void>;

export function RemoveIgnoreEntry(arg1:string):Promise<void>;

export function ResumeCapture():Promise<void>;

export function SetGhostMode(arg1:boolean):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateClipContent(arg1:number,arg2:string):Promise<void>;

export function UpdateStorageLimit(arg1:number):Promise<void>;
