// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeleteAllClips() {
  return window['go']['main']['App']['DeleteAllClips']();
}

export function DeletePinnedClips() {
  return window['go']['main']['App']['DeletePinnedClips']();
}

export function DeleteUnpinnedClips() {
  return window['go']['main']['App']['DeleteUnpinnedClips']();
}

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function GetStorageLimit() {
  return window['go']['main']['App']['GetStorageLimit']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function UpdateStorageLimit(arg1) {
  return window['go']['main']['App']['UpdateStorageLimit'](arg1);
}
